# Generated by Django 4.0.4 on 2022-05-27 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('telefone', models.IntegerField(max_length=100)),
                ('endereco', models.CharField(max_length=100)),
                ('profissao', models.CharField(max_length=100)),
            ],
        ),
    ]
